### ISSUE TITLE
Test AKS installer against 1.24/1.25 version

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-aks-installer#14]
As per title, we should test and update accordingly

**Comment by ralgozino** [comment]
As per our call @smerlos:
- There's no integration with furyctl for the AKS installer.
- Let's upgrade the `terraform` providers but we need to keep the Terraform version pinned at `0.15.4`
- These two Fury modules have integrations with AKS and might need to be updated:
  - DR: [Velero AKS Plugin](https://github.com/sighupio/fury-kubernetes-dr/tree/main/katalog/velero/velero-azure) and [Velero AKS Terraform](https://github.com/sighupio/fury-kubernetes-dr/tree/main/modules/azure-velero)
  - Monitoring: [AKS Service Monitor](https://github.com/sighupio/fury-kubernetes-monitoring/tree/main/katalog/aks-sm)

**Comment by smerlos** [comment]
Hi there,

I have thoroughly reviewed issue #14 and unfortunately, I was unable to carry out the necessary testing due to the module not functioning properly and insufficient documentation. Additionally, the VPN has not been configured, which may be contributing to the issue.

The recommendation is to have two separate modules - one for creating the Kubernetes cluster(reference #16) and another for creating the networks and VPN (reference #11). This will help improve the overall functionality and ease of use of the system.
